### ISSUE TITLE
i run into the following with v1 and v1.08

### ISSUE THREAD

**Issue by whoissqr** [SecureCodeWarrior/github-action-add-sarif-contextual-training#202]
i run into the following with v1 and v1.08.
```
Run SecureCodeWarrior/github-action-add-sarif-contextual-training@v1.08
govwaSARIF.json

/home/runner/work/_actions/SecureCodeWarrior/github-action-add-sarif-contextual-training/v1.08/webpack:/github-action-add-sarif-contextual-training/runner.js:64
        onFailure(error.message);
^
TypeError: onFailure is not a function
    at run (/home/runner/work/_actions/SecureCodeWarrior/github-action-add-sarif-contextual-training/v1.08/webpack:/github-action-add-sarif-contextual-training/runner.js:64:1)
```

can you advise? thanks!

**Comment by cwong-scw** [comment]
Thank you @whoissqr for reporting this issue to us. We have deployed an update that should address the issue. Please try to run it again with v1.10 (or v1) and let us know if you are still running into this error.

**Comment by whoissqr** [comment]
@cwong-scw  thank you for the quick response. I tried v1.10 just now and met a new issue. I am guessing this is due to the fact my SARIF has reference to files which are not present in the current source repo.

```
Error: TypeError: Cannot read properties of undefined (reading 'get')
govwaSARIF.json
Error: ENOENT: no such file or directory, open 'sarif/findings.processed.sarif'
Error: ENOENT: no such file or directory, open 'sarif/findings.processed.sarif'
```

**Comment by whoissqr** [comment]
@cwong-scw  thank you for the quick response.

https://github.com/whoissqr/govwa-coverity-SARIF/blob/master/.github/workflows/sast-github-hosted.yml

with v1.10, I got 
```
Error: TypeError: Cannot read properties of undefined (reading 'get')
govwaSARIF.json
Error: ENOENT: no such file or directory, open 'sarif/findings.processed.sarif'
Error: ENOENT: no such file or directory, open 'sarif/findings.processed.sarif'
```
is *.json allowed as input?

**Comment by cwong-scw** [comment]
@whoissqr Thanks for providing additional details.

I believe the TypeError can be ignored. We have a remaining todo to clean that up but it should not affect the Action functionality. .json file input is supported so that should not be the cause of the issue.

Would you be able to provide the full log for the "Add SCW Training" and "Upload SARIF file" steps of the workflow?

**Comment by whoissqr** [comment]
Here you go:
```
2023-07-18T07:45:04.7536162Z ##[group]Run SecureCodeWarrior/github-action-add-sarif-contextual-training@v1.10
2023-07-18T07:45:04.7537059Z with:
2023-07-18T07:45:04.7537757Z   inputSarifFile: govwaSARIF.json
2023-07-18T07:45:04.7538633Z   outputSarifFile: sarif/findings.processed.sarif
2023-07-18T07:45:04.7539662Z   githubToken: ***
2023-07-18T07:45:04.7540296Z env:
2023-07-18T07:45:04.7541117Z   COVERITY_URL: ***
2023-07-18T07:45:04.7541805Z   COV_USER: ***
2023-07-18T07:45:04.7542537Z   COVERITY_PASSPHRASE: ***
2023-07-18T07:45:04.7554729Z   LICENSE: ***
2023-07-18T07:45:04.7555563Z   COVERITY_TOOLKIT: cov-analysis-linux64-2023.6.0
2023-07-18T07:45:04.7556481Z   GOROOT: /opt/hostedtoolcache/go/1.15.15/x64
2023-07-18T07:45:04.7557227Z ##[endgroup]
2023-07-18T07:45:04.8593672Z ##[error]TypeError: Cannot read properties of undefined (reading 'get')
2023-07-18T07:45:04.8631652Z govwaSARIF.json
2023-07-18T07:45:11.0875887Z ##[error]ENOENT: no such file or directory, open 'sarif/findings.processed.sarif'
2023-07-18T07:45:11.0881805Z Error: ENOENT: no such file or directory, open 'sarif/findings.processed.sarif'
2023-07-18T07:45:11.1036727Z Post job cleanup.
2023-07-18T07:45:11.2382835Z [command]/usr/bin/git version
2023-07-18T07:45:11.2433236Z git version 2.41.0
2023-07-18T07:45:11.2478708Z Temporarily overriding HOME='/home/runner/work/_temp/42ddfe03-73e9-42be-914e-b2be833e9407' before making global git config changes
2023-07-18T07:45:11.2480227Z Adding repository directory to the temporary git global config as a safe directory
2023-07-18T07:45:11.2484744Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF
2023-07-18T07:45:11.2524362Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-07-18T07:45:11.2560691Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-07-18T07:45:11.2797455Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2023-07-18T07:45:11.2823398Z http.https://github.com/.extraheader
2023-07-18T07:45:11.2836318Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2023-07-18T07:45:11.2871843Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2023-07-18T07:45:11.3339792Z Cleaning up orphan processes
```

**Comment by cwong-scw** [comment]
Thank you @whoissqr. We will investigate further and get back to you.

**Comment by cwong-scw** [comment]
One last information request if you don't mind 🙏 

Can you please run it again with ACTIONS_STEP_DEBUG set to `true` in order to enable debug logging and then provide the output log for the same two steps?

This can be set either as a variable or a secret in your repository settings: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging

**Comment by whoissqr** [comment]
sure @cwong-scw 
```
2023-07-18T12:45:30.9038227Z ##[group]Run SecureCodeWarrior/github-action-add-sarif-contextual-training@v1.10
2023-07-18T12:45:30.9039267Z with:
2023-07-18T12:45:30.9040058Z   inputSarifFile: govwaSARIF.json
2023-07-18T12:45:30.9041038Z   outputSarifFile: sarif/findings.processed.sarif
2023-07-18T12:45:30.9042173Z   githubToken: ***
2023-07-18T12:45:30.9042908Z env:
2023-07-18T12:45:30.9043841Z   COVERITY_URL: ***
2023-07-18T12:45:30.9044610Z   COV_USER: ***
2023-07-18T12:45:30.9045445Z   COVERITY_PASSPHRASE: ***
2023-07-18T12:45:30.9060043Z   LICENSE: ***
2023-07-18T12:45:30.9060973Z   COVERITY_TOOLKIT: cov-analysis-linux64-2023.6.0
2023-07-18T12:45:30.9061904Z   ACTIONS_STEP_DEBUG: true
2023-07-18T12:45:30.9062822Z   GOROOT: /opt/hostedtoolcache/go/1.15.15/x64
2023-07-18T12:45:30.9063673Z ##[endgroup]
2023-07-18T12:45:31.0110185Z ##[error]TypeError: Cannot read properties of undefined (reading 'get')
2023-07-18T12:45:31.0135361Z govwaSARIF.json
2023-07-18T12:45:35.4664247Z ##[error]ENOENT: no such file or directory, open 'sarif/findings.processed.sarif'
2023-07-18T12:45:35.4671187Z Error: ENOENT: no such file or directory, open 'sarif/findings.processed.sarif'
2023-07-18T12:45:35.4819135Z Post job cleanup.
2023-07-18T12:45:35.6179287Z [command]/usr/bin/git version
2023-07-18T12:45:35.6240220Z git version 2.41.0
2023-07-18T12:45:35.6302060Z Temporarily overriding HOME='/home/runner/work/_temp/5bbc93e7-8a81-464d-b818-896022d9878a' before making global git config changes
2023-07-18T12:45:35.6308187Z Adding repository directory to the temporary git global config as a safe directory
2023-07-18T12:45:35.6320412Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF
2023-07-18T12:45:35.6370364Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-07-18T12:45:35.6414634Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-07-18T12:45:35.6685136Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2023-07-18T12:45:35.6705548Z http.https://github.com/.extraheader
2023-07-18T12:45:35.6720219Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2023-07-18T12:45:35.6779190Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2023-07-18T12:45:35.7260423Z Cleaning up orphan processes
```

**Comment by cwong-scw** [comment]
Unfortunately, we have been unable to reproduce the issue so far. All our testing completes successfully, although we do not have access to Coverity to test with it specifically.

We've pushed some additional updates to clean up the TypeError and to add some extra error logging when writing to the output file, as that appears to be where you are encountering the ENOENT error. I also noticed that the `ACTIONS_STEP_DEBUG` setting did not seem to take hold in your last run. I believe it needs to be configured in the settings section of the repository and cannot be included in the workflow configuration file itself:
![image](https://github.com/SecureCodeWarrior/github-action-add-sarif-contextual-training/assets/53287328/ef5e11fa-789f-43bd-8f13-be6b00eeb2f0)

You may need to push a dummy commit to force it to run again afterwards, but if you are able to provide the output with that setting enabled that would be very helpful. You should start seeing lines such as `##[debug]Evaluating condition for step: 'Add Secure Code Warrior contextual training to SARIF'`. 

Also, please use `@v1` instead of `@v1.10` to track the latest v1 changes as I have not made specific versions yet. We appreciate your patience and help to work with us in debugging this issue.

**Comment by whoissqr** [comment]
no worries, I am happy to help debugging this issue.

I enabled debugging via github action secret, modified workflow to use v1 instead of v1.10, and then captured the log again.

```
2023-07-19T02:59:12.2213966Z ##[debug]Finishing: Convert to SARIF
2023-07-19T02:59:12.2222424Z ##[debug]Evaluating condition for step: 'Add SCW Training'
2023-07-19T02:59:12.2224379Z ##[debug]Evaluating: success()
2023-07-19T02:59:12.2225503Z ##[debug]Evaluating success:
2023-07-19T02:59:12.2226578Z ##[debug]=> true
2023-07-19T02:59:12.2227645Z ##[debug]Result: true
2023-07-19T02:59:12.2228942Z ##[debug]Starting: Add SCW Training
2023-07-19T02:59:12.2255682Z ##[debug]Loading inputs
2023-07-19T02:59:12.2257631Z ##[debug]Evaluating: secrets.GITHUB_TOKEN
2023-07-19T02:59:12.2258489Z ##[debug]Evaluating Index:
2023-07-19T02:59:12.2259291Z ##[debug]..Evaluating secrets:
2023-07-19T02:59:12.2260083Z ##[debug]..=> Object
2023-07-19T02:59:12.2260882Z ##[debug]..Evaluating String:
2023-07-19T02:59:12.2261673Z ##[debug]..=> 'GITHUB_TOKEN'
2023-07-19T02:59:12.2262731Z ##[debug]=> '***'
2023-07-19T02:59:12.2263694Z ##[debug]Result: '***'
2023-07-19T02:59:12.2264556Z ##[debug]Loading env
2023-07-19T02:59:12.2276936Z ##[group]Run SecureCodeWarrior/github-action-add-sarif-contextual-training@v1
2023-07-19T02:59:12.2277895Z with:
2023-07-19T02:59:12.2278642Z   inputSarifFile: govwaSARIF.json
2023-07-19T02:59:12.2279581Z   outputSarifFile: sarif/findings.processed.sarif
2023-07-19T02:59:12.2280662Z   githubToken: ***
2023-07-19T02:59:12.2281344Z env:
2023-07-19T02:59:12.2282204Z   COVERITY_URL: ***
2023-07-19T02:59:12.2282940Z   COV_USER: ***
2023-07-19T02:59:12.2283724Z   COVERITY_PASSPHRASE: ***
2023-07-19T02:59:12.2296433Z   LICENSE: ***
2023-07-19T02:59:12.2297326Z   COVERITY_TOOLKIT: cov-analysis-linux64-2023.6.0
2023-07-19T02:59:12.2298212Z   ACTIONS_STEP_DEBUG: true
2023-07-19T02:59:12.2299072Z   GOROOT: /opt/hostedtoolcache/go/1.15.15/x64
2023-07-19T02:59:12.2300085Z ##[endgroup]
2023-07-19T02:59:12.3115410Z ##[debug]Input path type: file
2023-07-19T02:59:12.3147502Z govwaSARIF.json
2023-07-19T02:59:12.3149500Z ##[debug]Loading file: govwaSARIF.json
2023-07-19T02:59:18.2657988Z ##[debug]Writing file: sarif/findings.processed.sarif
2023-07-19T02:59:18.2692122Z Error writing file: sarif/findings.processed.sarif [Error: ENOENT: no such file or directory, open 'sarif/findings.processed.sarif'] {
2023-07-19T02:59:18.2693484Z   errno: -2,
2023-07-19T02:59:18.2694444Z   code: 'ENOENT',
2023-07-19T02:59:18.2695663Z   syscall: 'open',
2023-07-19T02:59:18.2696587Z   path: 'sarif/findings.processed.sarif'
2023-07-19T02:59:18.2697337Z }
2023-07-19T02:59:18.2766086Z ##[debug]Node Action run completed with exit code 0
2023-07-19T02:59:18.2769346Z ##[debug]Finishing: Add SCW Training
2023-07-19T02:59:18.2778392Z ##[debug]Evaluating condition for step: 'Upload SARIF file'
2023-07-19T02:59:18.2780334Z ##[debug]Evaluating: success()
2023-07-19T02:59:18.2781482Z ##[debug]Evaluating success:
2023-07-19T02:59:18.2782532Z ##[debug]=> true
2023-07-19T02:59:18.2783596Z ##[debug]Result: true
2023-07-19T02:59:18.2784875Z ##[debug]Starting: Upload SARIF file
2023-07-19T02:59:18.2815538Z ##[debug]Loading inputs
2023-07-19T02:59:18.2832834Z ##[debug]Evaluating: github.workspace
2023-07-19T02:59:18.2833704Z ##[debug]Evaluating Index:
2023-07-19T02:59:18.2834491Z ##[debug]..Evaluating github:
2023-07-19T02:59:18.2835258Z ##[debug]..=> Object
2023-07-19T02:59:18.2836049Z ##[debug]..Evaluating String:
2023-07-19T02:59:18.2836818Z ##[debug]..=> 'workspace'
2023-07-19T02:59:18.2837823Z ##[debug]=> '/home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF'
2023-07-19T02:59:18.2838978Z ##[debug]Result: '/home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF'
2023-07-19T02:59:18.2842375Z ##[debug]Evaluating: github.token
2023-07-19T02:59:18.2843201Z ##[debug]Evaluating Index:
2023-07-19T02:59:18.2843978Z ##[debug]..Evaluating github:
2023-07-19T02:59:18.2844753Z ##[debug]..=> Object
2023-07-19T02:59:18.2845527Z ##[debug]..Evaluating String:
2023-07-19T02:59:18.2846281Z ##[debug]..=> 'token'
2023-07-19T02:59:18.2847313Z ##[debug]=> '***'
2023-07-19T02:59:18.2848271Z ##[debug]Result: '***'
2023-07-19T02:59:18.2850332Z ##[debug]Evaluating: toJson(matrix)
2023-07-19T02:59:18.2851161Z ##[debug]Evaluating toJson:
2023-07-19T02:59:18.2883360Z ##[debug]..Evaluating matrix:
2023-07-19T02:59:18.2884177Z ##[debug]..=> null
2023-07-19T02:59:18.2887968Z ##[debug]=> 'null'
2023-07-19T02:59:18.2888725Z ##[debug]Result: 'null'
2023-07-19T02:59:18.2891337Z ##[debug]Loading env
2023-07-19T02:59:18.2902650Z ##[group]Run github/codeql-action/upload-sarif@v2
2023-07-19T02:59:18.2903452Z with:
2023-07-19T02:59:18.2904232Z   sarif_file: sarif/findings.processed.sarif
2023-07-19T02:59:18.2905014Z   category: Coverity
2023-07-19T02:59:18.2905972Z   checkout_path: /home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF
2023-07-19T02:59:18.2907072Z   token: ***
2023-07-19T02:59:18.2907749Z   matrix: null
2023-07-19T02:59:18.2908480Z   wait-for-processing: true
2023-07-19T02:59:18.2909179Z env:
2023-07-19T02:59:18.2910029Z   COVERITY_URL: ***
2023-07-19T02:59:18.2910737Z   COV_USER: ***
2023-07-19T02:59:18.2911502Z   COVERITY_PASSPHRASE: ***
2023-07-19T02:59:18.2923806Z   LICENSE: ***
2023-07-19T02:59:18.2924671Z   COVERITY_TOOLKIT: cov-analysis-linux64-2023.6.0
2023-07-19T02:59:18.2925547Z   ACTIONS_STEP_DEBUG: true
2023-07-19T02:59:18.2926403Z   GOROOT: /opt/hostedtoolcache/go/1.15.15/x64
2023-07-19T02:59:18.2927174Z ##[endgroup]
2023-07-19T02:59:19.2860684Z ##[debug]Sending status report: {"job_run_uuid":"","workflow_run_id":5594460432,"workflow_run_attempt":1,"workflow_name":"sast-github-hosted","job_name":"SAST","analysis_key":".github/workflows/sast-github-hosted.yml:SAST","commit_oid":"fcba5ae8dfe469af8810f386d0efc588b217be91","ref":"refs/heads/master","action_name":"upload-sarif","action_ref":"v2","action_oid":"unknown","started_at":"2023-07-19T02:59:18.729Z","action_started_at":"2023-07-19T02:59:18.729Z","status":"starting","testing_environment":"","runner_os":"Linux","action_version":"2.20.4","matrix_vars":"null","runner_arch":"X64"}
2023-07-19T02:59:19.6068446Z ##[error]Path does not exist: sarif/findings.processed.sarif
2023-07-19T02:59:19.6092692Z Error: Path does not exist: sarif/findings.processed.sarif
2023-07-19T02:59:19.6094313Z     at getSarifFilePaths (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:141:15)
2023-07-19T02:59:19.6096315Z     at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:136:30)
2023-07-19T02:59:19.6097811Z     at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:48:47)
2023-07-19T02:59:19.6099760Z     at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:70:9)
2023-07-19T02:59:19.6123896Z ##[debug]Sending status report: {"job_run_uuid":"","workflow_run_id":5594460432,"workflow_run_attempt":1,"workflow_name":"sast-github-hosted","job_name":"SAST","analysis_key":".github/workflows/sast-github-hosted.yml:SAST","commit_oid":"fcba5ae8dfe469af8810f386d0efc588b217be91","ref":"refs/heads/master","action_name":"upload-sarif","action_ref":"v2","action_oid":"unknown","started_at":"2023-07-19T02:59:18.729Z","action_started_at":"2023-07-19T02:59:18.729Z","status":"failure","testing_environment":"","runner_os":"Linux","action_version":"2.20.4","cause":"Path does not exist: sarif/findings.processed.sarif","exception":"Error: Path does not exist: sarif/findings.processed.sarif\n    at getSarifFilePaths (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:141:15)\n    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:136:30)\n    at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:48:47)\n    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:70:9)","completed_at":"2023-07-19T02:59:19.605Z","matrix_vars":"null","runner_arch":"X64"}
2023-07-19T02:59:19.9360752Z ##[debug]Node Action run completed with exit code 1
2023-07-19T02:59:19.9364803Z ##[debug]CODEQL_ACTION_FEATURE_MULTI_LANGUAGE='false'
2023-07-19T02:59:19.9365811Z ##[debug]CODEQL_ACTION_FEATURE_SANDWICH='false'
2023-07-19T02:59:19.9366791Z ##[debug]CODEQL_ACTION_FEATURE_SARIF_COMBINE='true'
2023-07-19T02:59:19.9367789Z ##[debug]CODEQL_ACTION_FEATURE_WILL_UPLOAD='true'
2023-07-19T02:59:19.9368705Z ##[debug]CODEQL_ACTION_VERSION='2.20.4'
2023-07-19T02:59:19.9369794Z ##[debug]CODEQL_ACTION_ANALYSIS_KEY='.github/workflows/sast-github-hosted.yml:SAST'
2023-07-19T02:59:19.9370927Z ##[debug]CODEQL_WORKFLOW_STARTED_AT='2023-07-19T02:59:18.729Z'
2023-07-19T02:59:19.9376759Z ##[debug]Finishing: Upload SARIF file
2023-07-19T02:59:19.9398646Z ##[debug]Evaluating condition for step: 'Test'
2023-07-19T02:59:19.9401360Z ##[debug]Evaluating: success()
2023-07-19T02:59:19.9402505Z ##[debug]Evaluating success:
2023-07-19T02:59:19.9403823Z ##[debug]=> false
2023-07-19T02:59:19.9405032Z ##[debug]Result: false
2023-07-19T02:59:19.9412214Z ##[debug]Evaluating condition for step: 'Post Run actions/checkout@v2'
2023-07-19T02:59:19.9415720Z ##[debug]Evaluating: always()
2023-07-19T02:59:19.9416805Z ##[debug]Evaluating always:
2023-07-19T02:59:19.9418413Z ##[debug]=> true
2023-07-19T02:59:19.9419570Z ##[debug]Result: true
2023-07-19T02:59:19.9420979Z ##[debug]Starting: Post Run actions/checkout@v2
2023-07-19T02:59:19.9457923Z ##[debug]Loading inputs
2023-07-19T02:59:19.9459776Z ##[debug]Evaluating: github.repository
2023-07-19T02:59:19.9460624Z ##[debug]Evaluating Index:
2023-07-19T02:59:19.9461430Z ##[debug]..Evaluating github:
2023-07-19T02:59:19.9462216Z ##[debug]..=> Object
2023-07-19T02:59:19.9463038Z ##[debug]..Evaluating String:
2023-07-19T02:59:19.9463813Z ##[debug]..=> 'repository'
2023-07-19T02:59:19.9464888Z ##[debug]=> 'whoissqr/govwa-coverity-SARIF'
2023-07-19T02:59:19.9465886Z ##[debug]Result: 'whoissqr/govwa-coverity-SARIF'
2023-07-19T02:59:19.9468779Z ##[debug]Evaluating: github.token
2023-07-19T02:59:19.9469632Z ##[debug]Evaluating Index:
2023-07-19T02:59:19.9470419Z ##[debug]..Evaluating github:
2023-07-19T02:59:19.9471185Z ##[debug]..=> Object
2023-07-19T02:59:19.9471946Z ##[debug]..Evaluating String:
2023-07-19T02:59:19.9472663Z ##[debug]..=> 'token'
2023-07-19T02:59:19.9473694Z ##[debug]=> '***'
2023-07-19T02:59:19.9474656Z ##[debug]Result: '***'
2023-07-19T02:59:19.9483211Z ##[debug]Loading env
2023-07-19T02:59:19.9496668Z Post job cleanup.
2023-07-19T02:59:20.0823028Z ##[debug]Getting git version
2023-07-19T02:59:20.0845044Z [command]/usr/bin/git version
2023-07-19T02:59:20.0906916Z git version 2.41.0
2023-07-19T02:59:20.0933372Z ##[debug]Set git useragent to: git/2.41.0 (github-actions-checkout)
2023-07-19T02:59:20.0945326Z ::add-mask::***
2023-07-19T02:59:20.0964889Z Temporarily overriding HOME='/home/runner/work/_temp/ec2b7f77-452a-4478-b70c-4d58200e5d5e' before making global git config changes
2023-07-19T02:59:20.0970776Z Adding repository directory to the temporary git global config as a safe directory
2023-07-19T02:59:20.0980291Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF
2023-07-19T02:59:20.1023678Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-07-19T02:59:20.1063132Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-07-19T02:59:20.1318407Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2023-07-19T02:59:20.1343967Z http.https://github.com/.extraheader
2023-07-19T02:59:20.1356637Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2023-07-19T02:59:20.1403795Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2023-07-19T02:59:20.1639017Z ##[debug]Unsetting HOME override
2023-07-19T02:59:20.1703862Z ##[debug]Node Action run completed with exit code 0
2023-07-19T02:59:20.1707159Z ##[debug]Finishing: Post Run actions/checkout@v2
2023-07-19T02:59:20.1833534Z ##[debug]Starting: Complete job
2023-07-19T02:59:20.1836321Z Cleaning up orphan processes
2023-07-19T02:59:20.2103276Z ##[debug]Finishing: Complete job
2023-07-19T02:59:20.2236498Z ##[debug]Finishing: SAST
```

**Comment by cwong-scw** [comment]
Thanks @whoissqr. We believe we have found the source of your issue and it is related to the supplied `outputSarifFile` value of `sarif/findings.processed.sarif`. The Action will not create directories that are missing and therefore expects the `sarif/` directory to already exist. Would you be able to please try modifying your workflow file to remove `sarif/` from the `outputSarifFile` on [line 61](https://github.com/whoissqr/govwa-coverity-SARIF/blob/fcba5ae8dfe469af8810f386d0efc588b217be91/.github/workflows/sast-github-hosted.yml#L61), and also from `sarif_file` on [line 67](https://github.com/whoissqr/govwa-coverity-SARIF/blob/fcba5ae8dfe469af8810f386d0efc588b217be91/.github/workflows/sast-github-hosted.yml#L67), and seeing if that resolves the issue?

**Comment by whoissqr** [comment]
thank you so much @cwong-scw  yes, that is the root cause, and it resolved the issue!

**Comment by cwong-scw** [comment]
Great to hear! Thank you @whoissqr! We will close out this issue.
