### ISSUE TITLE
no SARIF output when trying to process multiple SARIF inputs

### ISSUE THREAD

**Issue by whoissqr** [SecureCodeWarrior/github-action-add-sarif-contextual-training#210]
I am trying to process multiple SARIF input with SCW github action and it seems no output are generated; how do I troubleshoot this one?

```
    - name: Add SCW Training
      uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@v1
      with:
        inputSarifFile: ./sarifs
        outputSarifFile: ./processed-sarifs
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    
    - name: list processed SARIF files
      run: |
        echo 'SARIF input . . .'
        ls ./sarifs
        echo 'SARIFoutput . . .'
        ls ./processed-sarifs
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ./processed-sarifs
        category: AppSec
```
Logs from Action:
```
2023-07-27T06:56:56.0101832Z ##[debug]Evaluating condition for step: 'Convert to SARIF'
2023-07-27T06:56:56.0104465Z ##[debug]Evaluating: success()
2023-07-27T06:56:56.0105871Z ##[debug]Evaluating success:
2023-07-27T06:56:56.0107287Z ##[debug]=> true
2023-07-27T06:56:56.0108692Z ##[debug]Result: true
2023-07-27T06:56:56.0110365Z ##[debug]Starting: Convert to SARIF
2023-07-27T06:56:56.0126159Z ##[debug]Loading inputs
2023-07-27T06:56:56.0129856Z ##[debug]Evaluating: format('${{RUNNER_TEMP}}/${{COVERITY_TOOLKIT}}/node/bin/node ${{RUNNER_TEMP}}/${{COVERITY_TOOLKIT}}/SARIF/cov-format-sarif-for-github.js \
2023-07-27T06:56:56.0131320Z ##[debug]--inputFile govwa.json \
2023-07-27T06:56:56.0132455Z ##[debug]--outputFile ./sarifs/govwaSARIF.json \
2023-07-27T06:56:56.0133638Z ##[debug]--githubUrl https://github.com \
2023-07-27T06:56:56.0134742Z ##[debug]--repoName whoissqr/govwa \
2023-07-27T06:56:56.0135874Z ##[debug]--checkoutPath whoissqr/govwa {0} {1}
2023-07-27T06:56:56.0137077Z ##[debug]', github.workspace, github.sha)
2023-07-27T06:56:56.0138151Z ##[debug]Evaluating format:
2023-07-27T06:56:56.0139150Z ##[debug]..Evaluating String:
2023-07-27T06:56:56.0140674Z ##[debug]..=> '${{RUNNER_TEMP}}/${{COVERITY_TOOLKIT}}/node/bin/node ${{RUNNER_TEMP}}/${{COVERITY_TOOLKIT}}/SARIF/cov-format-sarif-for-github.js \
2023-07-27T06:56:56.0142059Z ##[debug]--inputFile govwa.json \
2023-07-27T06:56:56.0143186Z ##[debug]--outputFile ./sarifs/govwaSARIF.json \
2023-07-27T06:56:56.0144345Z ##[debug]--githubUrl https://github.com \
2023-07-27T06:56:56.0145437Z ##[debug]--repoName whoissqr/govwa \
2023-07-27T06:56:56.0146562Z ##[debug]--checkoutPath whoissqr/govwa {0} {1}
2023-07-27T06:56:56.0147540Z ##[debug]'
2023-07-27T06:56:56.0149104Z ##[debug]..Evaluating Index:
2023-07-27T06:56:56.0150155Z ##[debug]....Evaluating github:
2023-07-27T06:56:56.0151189Z ##[debug]....=> Object
2023-07-27T06:56:56.0152254Z ##[debug]....Evaluating String:
2023-07-27T06:56:56.0153233Z ##[debug]....=> 'workspace'
2023-07-27T06:56:56.0154620Z ##[debug]..=> '/home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF'
2023-07-27T06:56:56.0155915Z ##[debug]..Evaluating Index:
2023-07-27T06:56:56.0156916Z ##[debug]....Evaluating github:
2023-07-27T06:56:56.0158254Z ##[debug]....=> Object
2023-07-27T06:56:56.0159241Z ##[debug]....Evaluating String:
2023-07-27T06:56:56.0160209Z ##[debug]....=> 'sha'
2023-07-27T06:56:56.0161370Z ##[debug]..=> '29f0e20703313b2f1baaebfcbfdf301491b550dd'
2023-07-27T06:56:56.0162958Z ##[debug]=> '${RUNNER_TEMP}/${COVERITY_TOOLKIT}/node/bin/node ${RUNNER_TEMP}/${COVERITY_TOOLKIT}/SARIF/cov-format-sarif-for-github.js \
2023-07-27T06:56:56.0164333Z ##[debug]--inputFile govwa.json \
2023-07-27T06:56:56.0165669Z ##[debug]--outputFile ./sarifs/govwaSARIF.json \
2023-07-27T06:56:56.0166844Z ##[debug]--githubUrl https://github.com \
2023-07-27T06:56:56.0167932Z ##[debug]--repoName whoissqr/govwa \
2023-07-27T06:56:56.0169394Z ##[debug]--checkoutPath whoissqr/govwa /home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF 29f0e20703313b2f1baaebfcbfdf301491b550dd
2023-07-27T06:56:56.0170647Z ##[debug]'
2023-07-27T06:56:56.0172087Z ##[debug]Result: '${RUNNER_TEMP}/${COVERITY_TOOLKIT}/node/bin/node ${RUNNER_TEMP}/${COVERITY_TOOLKIT}/SARIF/cov-format-sarif-for-github.js \
2023-07-27T06:56:56.0173479Z ##[debug]--inputFile govwa.json \
2023-07-27T06:56:56.0174623Z ##[debug]--outputFile ./sarifs/govwaSARIF.json \
2023-07-27T06:56:56.0175772Z ##[debug]--githubUrl https://github.com \
2023-07-27T06:56:56.0176857Z ##[debug]--repoName whoissqr/govwa \
2023-07-27T06:56:56.0179048Z ##[debug]--checkoutPath whoissqr/govwa /home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF 29f0e20703313b2f1baaebfcbfdf301491b550dd
2023-07-27T06:56:56.0180607Z ##[debug]'
2023-07-27T06:56:56.0181704Z ##[debug]Loading env
2023-07-27T06:56:56.0199772Z ##[group]Run ${RUNNER_TEMP}/${COVERITY_TOOLKIT}/node/bin/node ${RUNNER_TEMP}/${COVERITY_TOOLKIT}/SARIF/cov-format-sarif-for-github.js \
2023-07-27T06:56:56.0201916Z [36;1m${RUNNER_TEMP}/${COVERITY_TOOLKIT}/node/bin/node ${RUNNER_TEMP}/${COVERITY_TOOLKIT}/SARIF/cov-format-sarif-for-github.js \[0m
2023-07-27T06:56:56.0203317Z [36;1m--inputFile govwa.json \[0m
2023-07-27T06:56:56.0204450Z [36;1m--outputFile ./sarifs/govwaSARIF.json \[0m
2023-07-27T06:56:56.0206061Z [36;1m--githubUrl https://github.com \[0m
2023-07-27T06:56:56.0207155Z [36;1m--repoName whoissqr/govwa \[0m
2023-07-27T06:56:56.0208612Z [36;1m--checkoutPath whoissqr/govwa /home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF 29f0e20703313b2f1baaebfcbfdf301491b550dd[0m
2023-07-27T06:56:56.0272735Z shell: /usr/bin/bash -e {0}
2023-07-27T06:56:56.0273649Z env:
2023-07-27T06:56:56.0274805Z   COVERITY_URL: ***
2023-07-27T06:56:56.0275723Z   COV_USER: ***
2023-07-27T06:56:56.0276704Z   COVERITY_PASSPHRASE: ***
2023-07-27T06:56:56.0291665Z   LICENSE: ***
2023-07-27T06:56:56.0292802Z   COVERITY_TOOLKIT: cov-analysis-linux64-2023.6.0
2023-07-27T06:56:56.0293863Z   DETECT_DIAGNOSTIC: true
2023-07-27T06:56:56.0294835Z   ACTIONS_STEP_DEBUG: true
2023-07-27T06:56:56.0295986Z   pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
2023-07-27T06:56:56.0297277Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib
2023-07-27T06:56:56.0298355Z ##[endgroup]
2023-07-27T06:56:56.0362815Z ##[debug]/usr/bin/bash -e /home/runner/work/_temp/484ebb20-c6d1-4399-91aa-6c92ce2aa959.sh
2023-07-27T06:56:56.1326160Z No --checkoutPath option was specified that matches the file "/home/runner/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/dsn.go"
2023-07-27T06:56:56.1352267Z No --checkoutPath option was specified that matches the file "/home/runner/go/pkg/mod/github.com/gorilla/sessions@v1.2.1/store.go"
2023-07-27T06:56:56.1443069Z No --checkoutPath option was specified that matches the file "/home/runner/go/pkg/mod/github.com/gorilla/securecookie@v1.1.1/securecookie.go"
2023-07-27T06:56:56.1814475Z No --checkoutPath option was specified that matches the file "/home/runner/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/infile.go"
2023-07-27T06:56:56.1823858Z No --checkoutPath option was specified that matches the file "/home/runner/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/auth.go"
2023-07-27T06:56:56.1830219Z No --checkoutPath option was specified that matches the file "/home/runner/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go"
2023-07-27T06:56:56.2032792Z No --checkoutPath option was specified that matches the file "/home/runner/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/packets.go"
2023-07-27T06:56:56.2035264Z No --checkoutPath option was specified that matches the file "/home/runner/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/buffer.go"
2023-07-27T06:56:56.2163880Z No --checkoutPath option was specified that matches the file "/home/runner/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connector.go"
2023-07-27T06:56:56.2427486Z No --checkoutPath option was specified that matches the file "/home/runner/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go"
2023-07-27T06:56:56.2574464Z ##[debug]Finishing: Convert to SARIF
2023-07-27T06:56:56.2584885Z ##[debug]Evaluating condition for step: 'Add SCW Training'
2023-07-27T06:56:56.2587458Z ##[debug]Evaluating: success()
2023-07-27T06:56:56.2588881Z ##[debug]Evaluating success:
2023-07-27T06:56:56.2590280Z ##[debug]=> true
2023-07-27T06:56:56.2591697Z ##[debug]Result: true
2023-07-27T06:56:56.2593390Z ##[debug]Starting: Add SCW Training
2023-07-27T06:56:56.2632243Z ##[debug]Loading inputs
2023-07-27T06:56:56.2634664Z ##[debug]Evaluating: secrets.GITHUB_TOKEN
2023-07-27T06:56:56.2635717Z ##[debug]Evaluating Index:
2023-07-27T06:56:56.2636711Z ##[debug]..Evaluating secrets:
2023-07-27T06:56:56.2637688Z ##[debug]..=> Object
2023-07-27T06:56:56.2659160Z ##[debug]..Evaluating String:
2023-07-27T06:56:56.2672424Z ##[debug]..=> 'GITHUB_TOKEN'
2023-07-27T06:56:56.2673851Z ##[debug]=> '***'
2023-07-27T06:56:56.2675097Z ##[debug]Result: '***'
2023-07-27T06:56:56.2676200Z ##[debug]Loading env
2023-07-27T06:56:56.2702696Z ##[group]Run SecureCodeWarrior/github-action-add-sarif-contextual-training@v1
2023-07-27T06:56:56.2703836Z with:
2023-07-27T06:56:56.2704731Z   inputSarifFile: ./sarifs
2023-07-27T06:56:56.2705773Z   outputSarifFile: ./processed-sarifs
2023-07-27T06:56:56.2707556Z   githubToken: ***
2023-07-27T06:56:56.2708483Z env:
2023-07-27T06:56:56.2709545Z   COVERITY_URL: ***
2023-07-27T06:56:56.2710446Z   COV_USER: ***
2023-07-27T06:56:56.2711402Z   COVERITY_PASSPHRASE: ***
2023-07-27T06:56:56.2727575Z   LICENSE: ***
2023-07-27T06:56:56.2728708Z   COVERITY_TOOLKIT: cov-analysis-linux64-2023.6.0
2023-07-27T06:56:56.2729757Z   DETECT_DIAGNOSTIC: true
2023-07-27T06:56:56.2730717Z   ACTIONS_STEP_DEBUG: true
2023-07-27T06:56:56.2731843Z   pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
2023-07-27T06:56:56.2733121Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib
2023-07-27T06:56:56.2734171Z ##[endgroup]
2023-07-27T06:56:56.3753885Z ##[debug]Input path type: directory
2023-07-27T06:56:56.3766860Z ./sarifs
2023-07-27T06:56:56.3858288Z ##[debug]Node Action run completed with exit code 0
2023-07-27T06:56:56.3862479Z ##[debug]Finishing: Add SCW Training
2023-07-27T06:56:56.3873880Z ##[debug]Evaluating condition for step: 'list processed SARIF files'
2023-07-27T06:56:56.3876624Z ##[debug]Evaluating: success()
2023-07-27T06:56:56.3878001Z ##[debug]Evaluating success:
2023-07-27T06:56:56.3879552Z ##[debug]=> true
2023-07-27T06:56:56.3880956Z ##[debug]Result: true
2023-07-27T06:56:56.3882689Z ##[debug]Starting: list processed SARIF files
2023-07-27T06:56:56.3898204Z ##[debug]Loading inputs
2023-07-27T06:56:56.3900175Z ##[debug]Loading env
2023-07-27T06:56:56.3913101Z ##[group]Run echo 'SARIF input . . .'
2023-07-27T06:56:56.3914167Z [36;1mecho 'SARIF input . . .'[0m
2023-07-27T06:56:56.3915130Z [36;1mls ./sarifs[0m
2023-07-27T06:56:56.3916172Z [36;1mecho 'SARIFoutput . . .'[0m
2023-07-27T06:56:56.3917198Z [36;1mls ./processed-sarifs[0m
2023-07-27T06:56:56.3982430Z shell: /usr/bin/bash -e {0}
2023-07-27T06:56:56.3983342Z env:
2023-07-27T06:56:56.3984591Z   COVERITY_URL: ***
2023-07-27T06:56:56.3985511Z   COV_USER: ***
2023-07-27T06:56:56.3986552Z   COVERITY_PASSPHRASE: ***
2023-07-27T06:56:56.4001942Z   LICENSE: ***
2023-07-27T06:56:56.4003064Z   COVERITY_TOOLKIT: cov-analysis-linux64-2023.6.0
2023-07-27T06:56:56.4004464Z   DETECT_DIAGNOSTIC: true
2023-07-27T06:56:56.4005666Z   ACTIONS_STEP_DEBUG: true
2023-07-27T06:56:56.4006796Z   pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
2023-07-27T06:56:56.4008062Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib
2023-07-27T06:56:56.4009108Z ##[endgroup]
2023-07-27T06:56:56.4073545Z ##[debug]/usr/bin/bash -e /home/runner/work/_temp/be58e5ca-ddf3-4469-b07b-1efb94c73366.sh
2023-07-27T06:56:56.4108551Z SARIF input . . .
2023-07-27T06:56:56.4125998Z bdSARIF.json
2023-07-27T06:56:56.4127086Z govwaSARIF.json
2023-07-27T06:56:56.4129701Z SARIFoutput . . .
2023-07-27T06:56:56.4149623Z ##[debug]Finishing: list processed SARIF files
2023-07-27T06:56:56.4161589Z ##[debug]Evaluating condition for step: 'Upload SARIF file'
2023-07-27T06:56:56.4163964Z ##[debug]Evaluating: success()
2023-07-27T06:56:56.4165573Z ##[debug]Evaluating success:
2023-07-27T06:56:56.4166945Z ##[debug]=> true
2023-07-27T06:56:56.4168395Z ##[debug]Result: true
2023-07-27T06:56:56.4170105Z ##[debug]Starting: Upload SARIF file
2023-07-27T06:56:56.4210755Z ##[debug]Loading inputs
2023-07-27T06:56:56.4213462Z ##[debug]Evaluating: github.workspace
2023-07-27T06:56:56.4214565Z ##[debug]Evaluating Index:
2023-07-27T06:56:56.4215559Z ##[debug]..Evaluating github:
2023-07-27T06:56:56.4216530Z ##[debug]..=> Object
2023-07-27T06:56:56.4217509Z ##[debug]..Evaluating String:
2023-07-27T06:56:56.4218487Z ##[debug]..=> 'workspace'
2023-07-27T06:56:56.4219760Z ##[debug]=> '/home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF'
2023-07-27T06:56:56.4221698Z ##[debug]Result: '/home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF'
2023-07-27T06:56:56.4226407Z ##[debug]Evaluating: github.token
2023-07-27T06:56:56.4227432Z ##[debug]Evaluating Index:
2023-07-27T06:56:56.4228418Z ##[debug]..Evaluating github:
2023-07-27T06:56:56.4229549Z ##[debug]..=> Object
2023-07-27T06:56:56.4230521Z ##[debug]..Evaluating String:
2023-07-27T06:56:56.4231465Z ##[debug]..=> 'token'
2023-07-27T06:56:56.4232809Z ##[debug]=> '***'
2023-07-27T06:56:56.4233975Z ##[debug]Result: '***'
2023-07-27T06:56:56.4236887Z ##[debug]Evaluating: toJson(matrix)
2023-07-27T06:56:56.4237906Z ##[debug]Evaluating toJson:
2023-07-27T06:56:56.4272338Z ##[debug]..Evaluating matrix:
2023-07-27T06:56:56.4273360Z ##[debug]..=> null
2023-07-27T06:56:56.4278148Z ##[debug]=> 'null'
2023-07-27T06:56:56.4279132Z ##[debug]Result: 'null'
2023-07-27T06:56:56.4282428Z ##[debug]Loading env
2023-07-27T06:56:56.4296207Z ##[group]Run github/codeql-action/upload-sarif@v2
2023-07-27T06:56:56.4297189Z with:
2023-07-27T06:56:56.4298110Z   sarif_file: ./processed-sarifs
2023-07-27T06:56:56.4299061Z   category: AppSec
2023-07-27T06:56:56.4300238Z   checkout_path: /home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF
2023-07-27T06:56:56.4301572Z   token: ***
2023-07-27T06:56:56.4302427Z   matrix: null
2023-07-27T06:56:56.4303348Z   wait-for-processing: true
2023-07-27T06:56:56.4304241Z env:
2023-07-27T06:56:56.4305311Z   COVERITY_URL: ***
2023-07-27T06:56:56.4306218Z   COV_USER: ***
2023-07-27T06:56:56.4307185Z   COVERITY_PASSPHRASE: ***
2023-07-27T06:56:56.4322852Z   LICENSE: ***
2023-07-27T06:56:56.4323982Z   COVERITY_TOOLKIT: cov-analysis-linux64-2023.6.0
2023-07-27T06:56:56.4325429Z   DETECT_DIAGNOSTIC: true
2023-07-27T06:56:56.4326410Z   ACTIONS_STEP_DEBUG: true
2023-07-27T06:56:56.4327541Z   pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
2023-07-27T06:56:56.4328811Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib
2023-07-27T06:56:56.4329866Z ##[endgroup]
2023-07-27T06:56:57.4321188Z ##[debug]Sending status report: {"job_run_uuid":"","workflow_run_id":5677479246,"workflow_run_attempt":1,"workflow_name":"sast-github-hosted","job_name":"SAST-SCA","analysis_key":".github/workflows/sast-github-hosted.yml:SAST-SCA","commit_oid":"29f0e20703313b2f1baaebfcbfdf301491b550dd","ref":"refs/heads/master","action_name":"upload-sarif","action_ref":"v2","action_oid":"unknown","started_at":"2023-07-27T06:56:56.833Z","action_started_at":"2023-07-27T06:56:56.833Z","status":"starting","testing_environment":"","runner_os":"Linux","action_version":"2.21.1","matrix_vars":"null","runner_arch":"X64"}
2023-07-27T06:56:57.7162809Z ##[error]No SARIF files found to upload in "./processed-sarifs".
2023-07-27T06:56:57.7189065Z Error: No SARIF files found to upload in "./processed-sarifs".
2023-07-27T06:56:57.7190858Z     at getSarifFilePaths (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:146:19)
2023-07-27T06:56:57.7195451Z     at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:135:30)
2023-07-27T06:56:57.7197771Z     at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:49:47)
2023-07-27T06:56:57.7199676Z     at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:71:9)
2023-07-27T06:56:57.7205182Z ##[debug]Sending status report: {"job_run_uuid":"","workflow_run_id":5677479246,"workflow_run_attempt":1,"workflow_name":"sast-github-hosted","job_name":"SAST-SCA","analysis_key":".github/workflows/sast-github-hosted.yml:SAST-SCA","commit_oid":"29f0e20703313b2f1baaebfcbfdf301491b550dd","ref":"refs/heads/master","action_name":"upload-sarif","action_ref":"v2","action_oid":"unknown","started_at":"2023-07-27T06:56:56.833Z","action_started_at":"2023-07-27T06:56:56.833Z","status":"failure","testing_environment":"","runner_os":"Linux","action_version":"2.21.1","cause":"No SARIF files found to upload in \"./processed-sarifs\".","exception":"Error: No SARIF files found to upload in \"./processed-sarifs\".\n    at getSarifFilePaths (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:146:19)\n    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:135:30)\n    at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:49:47)\n    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:71:9)","completed_at":"2023-07-27T06:56:57.719Z","matrix_vars":"null","runner_arch":"X64"}
2023-07-27T06:56:58.0200414Z ##[debug]Node Action run completed with exit code 1
2023-07-27T06:56:58.0206847Z ##[debug]CODEQL_ACTION_FEATURE_MULTI_LANGUAGE='false'
2023-07-27T06:56:58.0208100Z ##[debug]CODEQL_ACTION_FEATURE_SANDWICH='false'
2023-07-27T06:56:58.0209299Z ##[debug]CODEQL_ACTION_FEATURE_SARIF_COMBINE='true'
2023-07-27T06:56:58.0210497Z ##[debug]CODEQL_ACTION_FEATURE_WILL_UPLOAD='true'
2023-07-27T06:56:58.0211721Z ##[debug]CODEQL_ACTION_VERSION='2.21.1'
2023-07-27T06:56:58.0213056Z ##[debug]CODEQL_ACTION_ANALYSIS_KEY='.github/workflows/sast-github-hosted.yml:SAST-SCA'
2023-07-27T06:56:58.0214478Z ##[debug]CODEQL_WORKFLOW_STARTED_AT='2023-07-27T06:56:56.833Z'
2023-07-27T06:56:58.0221023Z ##[debug]Finishing: Upload SARIF file
2023-07-27T06:56:58.0250517Z ##[debug]Evaluating condition for step: 'Test'
2023-07-27T06:56:58.0252995Z ##[debug]Evaluating: success()
2023-07-27T06:56:58.0254378Z ##[debug]Evaluating success:
2023-07-27T06:56:58.0255837Z ##[debug]=> false
2023-07-27T06:56:58.0257229Z ##[debug]Result: false
2023-07-27T06:56:58.0266199Z ##[debug]Evaluating condition for step: 'Post Set up Python 3.9'
2023-07-27T06:56:58.0268384Z ##[debug]Evaluating: success()
2023-07-27T06:56:58.0269764Z ##[debug]Evaluating success:
2023-07-27T06:56:58.0271101Z ##[debug]=> false
2023-07-27T06:56:58.0272484Z ##[debug]Result: false
2023-07-27T06:56:58.0282501Z ##[debug]Evaluating condition for step: 'Post Set up Go'
2023-07-27T06:56:58.0284624Z ##[debug]Evaluating: success()
2023-07-27T06:56:58.0286511Z ##[debug]Evaluating success:
2023-07-27T06:56:58.0287844Z ##[debug]=> false
2023-07-27T06:56:58.0289364Z ##[debug]Result: false
2023-07-27T06:56:58.0297673Z ##[debug]Evaluating condition for step: 'Post Run actions/checkout@v2'
2023-07-27T06:56:58.0301147Z ##[debug]Evaluating: always()
2023-07-27T06:56:58.0302522Z ##[debug]Evaluating always:
2023-07-27T06:56:58.0304509Z ##[debug]=> true
2023-07-27T06:56:58.0306020Z ##[debug]Result: true
2023-07-27T06:56:58.0308024Z ##[debug]Starting: Post Run actions/checkout@v2
2023-07-27T06:56:58.0352828Z ##[debug]Loading inputs
2023-07-27T06:56:58.0354964Z ##[debug]Evaluating: github.repository
2023-07-27T06:56:58.0356000Z ##[debug]Evaluating Index:
2023-07-27T06:56:58.0356984Z ##[debug]..Evaluating github:
2023-07-27T06:56:58.0357944Z ##[debug]..=> Object
2023-07-27T06:56:58.0358945Z ##[debug]..Evaluating String:
2023-07-27T06:56:58.0359928Z ##[debug]..=> 'repository'
2023-07-27T06:56:58.0361144Z ##[debug]=> 'whoissqr/govwa-coverity-SARIF'
2023-07-27T06:56:58.0362338Z ##[debug]Result: 'whoissqr/govwa-coverity-SARIF'
2023-07-27T06:56:58.0367004Z ##[debug]Evaluating: github.token
2023-07-27T06:56:58.0386829Z ##[debug]Evaluating Index:
2023-07-27T06:56:58.0387874Z ##[debug]..Evaluating github:
2023-07-27T06:56:58.0389050Z ##[debug]..=> Object
2023-07-27T06:56:58.0390056Z ##[debug]..Evaluating String:
2023-07-27T06:56:58.0391035Z ##[debug]..=> 'token'
2023-07-27T06:56:58.0392303Z ##[debug]=> '***'
2023-07-27T06:56:58.0393529Z ##[debug]Result: '***'
2023-07-27T06:56:58.0405692Z ##[debug]Loading env
2023-07-27T06:56:58.0421293Z Post job cleanup.
2023-07-27T06:56:58.2022861Z ##[debug]Getting git version
2023-07-27T06:56:58.2047457Z [command]/usr/bin/git version
2023-07-27T06:56:58.2131076Z git version 2.41.0
2023-07-27T06:56:58.2163745Z ##[debug]Set git useragent to: git/2.41.0 (github-actions-checkout)
2023-07-27T06:56:58.2173462Z ::add-mask::***
2023-07-27T06:56:58.2198274Z Temporarily overriding HOME='/home/runner/work/_temp/27937b08-22f8-4356-8733-ed2805ab8adb' before making global git config changes
2023-07-27T06:56:58.2200406Z Adding repository directory to the temporary git global config as a safe directory
2023-07-27T06:56:58.2206369Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/govwa-coverity-SARIF/govwa-coverity-SARIF
2023-07-27T06:56:58.2257558Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-07-27T06:56:58.2302918Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-07-27T06:56:58.2631583Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2023-07-27T06:56:58.2666339Z http.https://github.com/.extraheader
2023-07-27T06:56:58.2682803Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2023-07-27T06:56:58.2743710Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2023-07-27T06:56:58.3014369Z ##[debug]Unsetting HOME override
2023-07-27T06:56:58.3128012Z ##[debug]Node Action run completed with exit code 0
2023-07-27T06:56:58.3132364Z ##[debug]Finishing: Post Run actions/checkout@v2
2023-07-27T06:56:58.3313669Z ##[debug]Starting: Complete job
2023-07-27T06:56:58.3321662Z Cleaning up orphan processes
2023-07-27T06:56:58.3701073Z ##[debug]Finishing: Complete job
2023-07-27T06:56:58.3889842Z ##[debug]Finishing: SAST-SCA
```

**Comment by cwong-scw** [comment]
Hi @whoissqr!

I just looked into this and it looks like by default when specifying a directory, the action only searches for `.sarif` files. Please try specifying a glob-style file path such as `./processed-sarifs/*.json` to process SARIF files with a `.json` extension and let us know if that resolves the issue.

Thanks!

**Comment by whoissqr** [comment]
It worked! 
 thank you for the help.@cwong-scw

**Comment by cwong-scw** [comment]
Great! Please let us know if you run into any other issues.
